name: structRFM
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy==1.24.3
  - pandas==2.0.3
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - tensorboard==2.14.0
  - tensorboardx==2.2
  - transformers==4.45.1
  - safetensors==0.5.2
  - datasets==3.1.0
  - einops==0.7.0
  - pip
  - pip:
    - torch>=2.0.1
    - BPfold
    - structRFM
    - transformers[torch]
    - tqdm
