name: Zfold
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://conda.rosettacommons.org
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - anyio=4.2.0=py38h06a4308_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38h06a4308_0
  - attrs=23.1.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38h06a4308_0
  - blas=2.121=mkl
  - blas-devel=3.9.0=21_linux64_mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=2.4.3=py38h06a4308_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=2.2.1=py38h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=py38h06a4308_0
  - cudatoolkit=11.3.1=ha36c431_9
  - cytoolz=0.12.2=py38h5eee18b_0
  - dask=2023.4.1=py38h06a4308_1
  - dask-core=2023.4.1=py38h06a4308_0
  - dask-jobqueue=0.8.2=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2023.4.1=py38h06a4308_1
  - exceptiongroup=1.2.0=py38h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2023.10.0=py38h06a4308_0
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.6.13=h85f3911_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py38h06a4308_1
  - ipykernel=6.28.0=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - ipywidgets=8.1.2=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.3=py38h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.0=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_console=6.6.3=py38h06a4308_0
  - jupyter_core=5.5.0=py38h06a4308_0
  - jupyter_events=0.8.0=py38h06a4308_0
  - jupyter_server=2.10.0=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab=4.0.11=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py38h06a4308_0
  - jupyterlab_widgets=3.0.10=py38h06a4308_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=21_linux64_mkl
  - libcblas=3.9.0=21_linux64_mkl
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=21_linux64_mkl
  - liblapacke=3.9.0=21_linux64_mkl
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.2=h4dfa4b3_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2024.0.0=ha957f24_49657
  - mkl-devel=2024.0.0=ha770c72_49657
  - mkl-include=2024.0.0=ha957f24_49657
  - msgpack-python=1.0.3=py38hd09550d_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.10.0=py38h06a4308_0
  - nbformat=5.9.2=py38h06a4308_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - nettle=3.6=he412f7d_0
  - notebook=7.0.8=py38h06a4308_0
  - notebook-shim=0.2.3=py38h06a4308_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.13=h7f8727e_0
  - overrides=7.4.0=py38h06a4308_0
  - packaging=23.2=py38h06a4308_0
  - pandas=2.0.3=py38h01efb38_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38hde6dc18_1
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pyrosetta=2024.10+release.2c36cbc=py38_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=h955ad1f_0
  - python-blosc=1.10.6=py38h51133e4_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-json-logger=2.0.7=py38h06a4308_0
  - python-lmdb=1.4.1=py38h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py38h06a4308_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=py38h06a4308_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py38h06a4308_0
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - scipy=1.10.1=py38h59b608b_3
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.11.0=h00ab1b0_1
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - tornado=6.3.3=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.10.0=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.43.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.10=py38h06a4308_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py38h06a4308_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - biopandas==0.5.1
      - biopython==1.83
      - bpfold==0.2.6
      - configparser==7.1.0
      - csvsort==1.6.1
      - datasets==3.1.0
      - dill==0.3.8
      - einops==0.7.0
      - executing==2.2.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - huggingface-hub==0.30.2
      - icecream==2.1.4
      - joblib==1.4.2
      - looseversion==1.1.2
      - mmtf-python==1.1.3
      - multidict==6.1.0
      - multiprocess==0.70.16
      - progressbar2==4.5.0
      - propcache==0.2.0
      - pyarrow==17.0.0
      - python-utils==3.8.2
      - pyxis==0.2.1
      - regex==2024.11.6
      - requests==2.32.3
      - rna-tools==3.23.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - simplejson==3.20.1
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - transformers==4.46.3
      - versioneer==0.29
      - wget==3.2
      - xxhash==3.5.0
      - yarl==1.15.2
